### ISSUE TITLE
KafkaProducer unable to send message

### ISSUE THREAD

**Issue by hwa123** [dpkp/kafka-python#1416]
I'm trying to deploy a function that pass message to another function, both are subscribed to different topics. When I ran the first function, one that actually produces message, I found the issue that kafkaProducer was unable to send message, it halted at waking up the sender. 

```
2018-03-08 07:21:17,901 - kafka.producer.kafka - DEBUG - Sending (key=None value={'foo': 'bar'}) to TopicPartition(topic='next_function_topic', partition=0)
2018-03-08 07:21:17,901 - kafka.producer.record_accumulator - DEBUG - Allocating a new 16384 byte message buffer for TopicPartition(topic='next_function_topic', partition=0)
2018-03-08 07:21:17,901 - kafka.producer.kafka - DEBUG - Waking up the sender since TopicPartition(topic='next_function_topic', partition=0) is either full or getting a new batch
```
Then it will throw a timeout message afterwards. 
The configs for KafkaProducer and actual codes for sending messges are:

```
producer = KafkaProducer(
    bootstrap_servers='kafka.kubeless:9092',
    value_serializer=lambda v: json.dumps(v).encode('utf-8'),
    api_version=(0, 10)
)

future = producer.send(next_function_topic, {'foo': 'bar'})
try:
    record_metadata = future.get()
except KafkaError as e:
    print e
```
What am I doing wrong here? Any comment is welcome. 

The runtime is py2.7, kafka-python is 1.4.1.

**Comment by dpkp** [comment]
Are you sure your producer was able to connect to `kafka.kubeless:9092` ? What do the logs say about connection success / failure? Being unable to connect to the cluster is the most common cause of a timeout here.

**Comment by hwa123** [comment]
Here is the full log and no connection error is found:

```
2018-03-12 03:19:35,917 - kafka.producer.kafka - DEBUG - Starting the Kafka producer
2018-03-12 03:19:35,918 - kafka.client - INFO - Bootstrapping cluster metadata from [('kafka.kubeless', 9092, 0)]
2018-03-12 03:19:35,919 - kafka.client - DEBUG - Attempting to bootstrap via node at kafka.kubeless:9092
2018-03-12 03:19:35,920 - kafka.conn - DEBUG - <BrokerConnection node_id=bootstrap host=kafka.kubeless/kafka.kubeless port=9092>: creating new socket
2018-03-12 03:19:35,921 - kafka.conn - DEBUG - <BrokerConnection node_id=bootstrap host=kafka.kubeless/10.101.119.96 port=9092>: setting socket option (6, 1, 1)
2018-03-12 03:19:35,921 - kafka.conn - INFO - <BrokerConnection node_id=bootstrap host=kafka.kubeless/10.101.119.96 port=9092>: connecting to 10.101.119.96:9092
2018-03-12 03:19:35,922 - kafka.conn - DEBUG - <BrokerConnection node_id=bootstrap host=kafka.kubeless/10.101.119.96 port=9092>: established TCP connection
2018-03-12 03:19:35,922 - kafka.conn - DEBUG - <BrokerConnection node_id=bootstrap host=kafka.kubeless/10.101.119.96 port=9092>: Connection complete.
2018-03-12 03:19:35,922 - kafka.client - DEBUG - Node bootstrap connected
2018-03-12 03:19:35,923 - kafka.conn - DEBUG - <BrokerConnection node_id=bootstrap host=kafka.kubeless/10.101.119.96 port=9092> Request 1: MetadataRequest_v1(topics=NULL)
2018-03-12 03:19:35,925 - kafka.conn - DEBUG - <BrokerConnection node_id=bootstrap host=kafka.kubeless/10.101.119.96 port=9092> Response 1: MetadataResponse_v1(brokers=[(node_id=1001, host=u'kafka-0.broker.kubeless.svc.cluster.local', port=9092, rack=None)], controller_id=1001, topics=[(error_code=0, topic=u’function_topic’, is_internal=False, partitions=[(error_code=0, partition=0, leader=1001, replicas=[1001], isr=[1001])]), (error_code=0, topic=u'next_function_topic', is_internal=False, partitions=[(error_code=0, partition=0, leader=1001, replicas=[1001], isr=[1001])]), (error_code=0, topic=u'__consumer_offsets', is_internal=True, partitions=[(error_code=0, partition=23, leader=1001, replicas=[1001], isr=[1001]), … (error_code=0, partition=0, leader=1001, replicas=[1001], isr=[1001])])])
2018-03-12 03:19:35,927 - kafka.cluster - DEBUG - Updated cluster metadata to ClusterMetadata(brokers: 1, topics: 3, groups: 0)
2018-03-12 03:19:35,927 - kafka.client - INFO - Bootstrap succeeded: found 1 brokers and 2 topics.
2018-03-12 03:19:35,927 - kafka.conn - INFO - <BrokerConnection node_id=bootstrap host=kafka.kubeless/10.101.119.96 port=9092>: Closing connection.
2018-03-12 03:19:35,927 - kafka.conn - DEBUG - <BrokerConnection node_id=bootstrap host=kafka.kubeless/10.101.119.96 port=9092>: reconnect backoff 0.0447254875102 after 1 failures
2018-03-12 03:19:35,931 - kafka.producer.sender - DEBUG - Starting Kafka producer I/O thread.
2018-03-12 03:19:35,931 - kafka.producer.kafka - DEBUG - Kafka producer started
2018-03-12 03:19:35,932 - kafka.client - INFO - Bootstrapping cluster metadata from [('kafka.kubeless', 9092, 0)]
2018-03-12 03:19:35,932 - kafka.client - DEBUG - Attempting to bootstrap via node at kafka.kubeless:9092
2018-03-12 03:19:35,933 - kafka.conn - DEBUG - <BrokerConnection node_id=bootstrap host=kafka.kubeless/kafka.kubeless port=9092>: creating new socket
2018-03-12 03:19:35,934 - kafka.conn - DEBUG - <BrokerConnection node_id=bootstrap host=kafka.kubeless/10.101.119.96 port=9092>: setting socket option (6, 1, 1)
2018-03-12 03:19:35,934 - kafka.conn - INFO - <BrokerConnection node_id=bootstrap host=kafka.kubeless/10.101.119.96 port=9092>: connecting to 10.101.119.96:9092
2018-03-12 03:19:35,934 - kafka.conn - DEBUG - <BrokerConnection node_id=bootstrap host=kafka.kubeless/10.101.119.96 port=9092>: established TCP connection
2018-03-12 03:19:35,934 - kafka.conn - DEBUG - <BrokerConnection node_id=bootstrap host=kafka.kubeless/10.101.119.96 port=9092>: Connection complete.
2018-03-12 03:19:35,934 - kafka.client - DEBUG - Node bootstrap connected
2018-03-12 03:19:35,935 - kafka.conn - DEBUG - <BrokerConnection node_id=bootstrap host=kafka.kubeless/10.101.119.96 port=9092> Request 1: MetadataRequest_v0(topics=[])
2018-03-12 03:19:35,936 - kafka.conn - DEBUG - <BrokerConnection node_id=bootstrap host=kafka.kubeless/10.101.119.96 port=9092> Response 1: MetadataResponse_v0(brokers=[(node_id=1001, host=u'kafka-0.broker.kubeless.svc.cluster.local', port=9092)], topics=[(error_code=0, topic=u’function_topic’, partitions=[(error_code=0, partition=0, leader=1001, replicas=[1001], isr=[1001])]), (error_code=0, topic=u'next_function_topic', partitions=[(error_code=0, partition=0, leader=1001, replicas=[1001], isr=[1001])]), (error_code=0, topic=u'__consumer_offsets', partitions=[(error_code=0, partition=23, leader=1001, replicas=[1001], isr=[1001]), …,  (error_code=0, partition=0, leader=1001, replicas=[1001], isr=[1001])])])
2018-03-12 03:19:35,937 - kafka.cluster - DEBUG - Updated cluster metadata to ClusterMetadata(brokers: 1, topics: 3, groups: 0)
2018-03-12 03:19:35,937 - kafka.client - INFO - Bootstrap succeeded: found 1 brokers and 3 topics.
2018-03-12 03:19:35,937 - kafka.conn - INFO - <BrokerConnection node_id=bootstrap host=kafka.kubeless/10.101.119.96 port=9092>: Closing connection.
2018-03-12 03:19:35,937 - kafka.conn - DEBUG - <BrokerConnection node_id=bootstrap host=kafka.kubeless/10.101.119.96 port=9092>: reconnect backoff 0.0557632162177 after 1 failures
2018-03-12 03:19:35,938 - kafka.client - DEBUG - Initiating connection to node 1001 at kafka-0.broker.kubeless.svc.cluster.local:9092
2018-03-12 03:19:35,938 - kafka.conn - DEBUG - <BrokerConnection node_id=1001 host=kafka-0.broker.kubeless.svc.cluster.local/kafka-0.broker.kubeless.svc.cluster.local port=9092>: creating new socket
2018-03-12 03:19:35,940 - kafka.conn - DEBUG - <BrokerConnection node_id=1001 host=kafka-0.broker.kubeless.svc.cluster.local/172.17.0.5 port=9092>: setting socket option (6, 1, 1)
2018-03-12 03:19:35,941 - kafka.conn - INFO - <BrokerConnection node_id=1001 host=kafka-0.broker.kubeless.svc.cluster.local/172.17.0.5 port=9092>: connecting to 172.17.0.5:9092
2018-03-12 03:19:35,941 - kafka.client - DEBUG - Node 1001 connected
2018-03-12 03:19:36,045 - kafka.conn - INFO - Broker version identifed as 0.11.0
2018-03-12 03:19:36,045 - kafka.conn - INFO - Set configuration api_version=(0, 11, 0) to skip auto check_version requests on startup
2018-03-12 03:19:36,047 - kafka.consumer.subscription_state - INFO - Updating subscribed topics to: [‘function_topic’]
2018-03-12 03:19:36,047 - kafka.consumer.group - DEBUG - Subscribed to topic(s): [‘function_topic’]
2018-03-12 03:19:36,047 - kafka.coordinator - DEBUG - Sending group coordinator request for group parsefoo to broker 1001
2018-03-12 03:19:36,048 - kafka.conn - DEBUG - <BrokerConnection node_id=1001 host=kafka-0.broker.kubeless.svc.cluster.local/172.17.0.5 port=9092> Request 3: GroupCoordinatorRequest_v0(consumer_group='parsefoo')
2018-03-12 03:19:36,048 - kafka.client - DEBUG - Sending metadata request MetadataRequest_v1(topics=[‘function_topic’]) to node 1001
2018-03-12 03:19:36,048 - kafka.conn - DEBUG - <BrokerConnection node_id=1001 host=kafka-0.broker.kubeless.svc.cluster.local/172.17.0.5 port=9092> Request 4: MetadataRequest_v1(topics=[‘function_topic’])
2018-03-12 03:19:36,049 - kafka.conn - DEBUG - <BrokerConnection node_id=1001 host=kafka-0.broker.kubeless.svc.cluster.local/172.17.0.5 port=9092> Response 3: GroupCoordinatorResponse_v0(error_code=0, coordinator_id=1001, host=u'kafka-0.broker.kubeless.svc.cluster.local', port=9092)
2018-03-12 03:19:36,049 - kafka.coordinator - DEBUG - Received group coordinator response GroupCoordinatorResponse_v0(error_code=0, coordinator_id=1001, host=u'kafka-0.broker.kubeless.svc.cluster.local', port=9092)
2018-03-12 03:19:36,049 - kafka.cluster - DEBUG - Updating coordinator for parsefoo: GroupCoordinatorResponse_v0(error_code=0, coordinator_id=1001, host=u'kafka-0.broker.kubeless.svc.cluster.local', port=9092)
2018-03-12 03:19:36,049 - kafka.cluster - INFO - Group coordinator for parsefoo is BrokerMetadata(nodeId=1001, host=u'kafka-0.broker.kubeless.svc.cluster.local', port=9092, rack=None)
2018-03-12 03:19:36,049 - kafka.coordinator - INFO - Discovered coordinator 1001 for group parsefoo
2018-03-12 03:19:36,049 - kafka.coordinator.consumer - INFO - Revoking previously assigned partitions set([]) for group parsefoo
2018-03-12 03:19:36,050 - kafka.conn - DEBUG - <BrokerConnection node_id=1001 host=kafka-0.broker.kubeless.svc.cluster.local/172.17.0.5 port=9092> Response 4: MetadataResponse_v1(brokers=[(node_id=1001, host=u'kafka-0.broker.kubeless.svc.cluster.local', port=9092, rack=None)], controller_id=1001, topics=[(error_code=0, topic=u’function_topic’, is_internal=False, partitions=[(error_code=0, partition=0, leader=1001, replicas=[1001], isr=[1001])])])
2018-03-12 03:19:36,050 - kafka.cluster - DEBUG - Updated cluster metadata to ClusterMetadata(brokers: 1, topics: 1, groups: 1)
2018-03-12 03:19:36,050 - kafka.coordinator - INFO - (Re-)joining group parsefoo
2018-03-12 03:19:36,050 - kafka.coordinator - DEBUG - Sending JoinGroup (JoinGroupRequest_v0(group='parsefoo', session_timeout=30000, member_id='', protocol_type='consumer', group_protocols=[(protocol_name='range', protocol_metadata='\x00\x00\x00\x00\x00\x01\x00 function_topic\x00\x00\x00\x00'), (protocol_name='roundrobin', protocol_metadata='\x00\x00\x00\x00\x00\x01\x00 function_topic\x00\x00\x00\x00')])) to coordinator 1001
2018-03-12 03:19:36,051 - kafka.conn - DEBUG - <BrokerConnection node_id=1001 host=kafka-0.broker.kubeless.svc.cluster.local/172.17.0.5 port=9092> Request 5: JoinGroupRequest_v0(group='parsefoo', session_timeout=30000, member_id='', protocol_type='consumer', group_protocols=[(protocol_name='range', protocol_metadata='\x00\x00\x00\x00\x00\x01\x00 function_topic\x00\x00\x00\x00'), (protocol_name='roundrobin', protocol_metadata='\x00\x00\x00\x00\x00\x01\x00 function_topic\x00\x00\x00\x00')])
2018-03-12 03:19:36,057 - kafka.conn - DEBUG - <BrokerConnection node_id=1001 host=kafka-0.broker.kubeless.svc.cluster.local/172.17.0.5 port=9092> Response 5: JoinGroupResponse_v0(error_code=0, generation_id=112, group_protocol=u'range', leader_id=u'kafka-python-1.3.5-1220fe0a-2275-40c9-bd0a-68ea3837824d', member_id=u'kafka-python-1.3.5-1220fe0a-2275-40c9-bd0a-68ea3837824d', members=[(member_id=u'kafka-python-1.3.5-1220fe0a-2275-40c9-bd0a-68ea3837824d', member_metadata='\x00\x00\x00\x00\x00\x01\x00 function_topic\x00\x00\x00\x00')])
2018-03-12 03:19:36,057 - kafka.coordinator - DEBUG - Received successful JoinGroup response for group parsefoo: JoinGroupResponse_v0(error_code=0, generation_id=112, group_protocol=u'range', leader_id=u'kafka-python-1.3.5-1220fe0a-2275-40c9-bd0a-68ea3837824d', member_id=u'kafka-python-1.3.5-1220fe0a-2275-40c9-bd0a-68ea3837824d', members=[(member_id=u'kafka-python-1.3.5-1220fe0a-2275-40c9-bd0a-68ea3837824d', member_metadata='\x00\x00\x00\x00\x00\x01\x00 function_topic\x00\x00\x00\x00')])
2018-03-12 03:19:36,057 - kafka.coordinator - INFO - Joined group 'parsefoo' (generation 112) with member_id kafka-python-1.3.5-1220fe0a-2275-40c9-bd0a-68ea3837824d
2018-03-12 03:19:36,058 - kafka.coordinator - INFO - Elected group leader -- performing partition assignments using range
2018-03-12 03:19:36,058 - kafka.coordinator.consumer - DEBUG - Performing assignment for group parsefoo using strategy range with subscriptions {u'kafka-python-1.3.5-1220fe0a-2275-40c9-bd0a-68ea3837824d': ConsumerProtocolMemberMetadata(version=0, subscription=[u’function_topic’], user_data='')}
2018-03-12 03:19:36,058 - kafka.coordinator.consumer - DEBUG - Finished assignment for group parsefoo: {u'kafka-python-1.3.5-1220fe0a-2275-40c9-bd0a-68ea3837824d': ConsumerProtocolMemberAssignment(version=0, assignment=[(topic=u’function_topic’, partitions=[0])], user_data='')}
2018-03-12 03:19:36,058 - kafka.coordinator - DEBUG - Sending leader SyncGroup for group parsefoo to coordinator 1001: SyncGroupRequest_v0(group='parsefoo', generation_id=112, member_id=u'kafka-python-1.3.5-1220fe0a-2275-40c9-bd0a-68ea3837824d', group_assignment=[(member_id=u'kafka-python-1.3.5-1220fe0a-2275-40c9-bd0a-68ea3837824d', member_metadata='\x00\x00\x00\x00\x00\x01\x00 function_topic\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00')])
2018-03-12 03:19:36,058 - kafka.conn - DEBUG - <BrokerConnection node_id=1001 host=kafka-0.broker.kubeless.svc.cluster.local/172.17.0.5 port=9092> Request 6: SyncGroupRequest_v0(group='parsefoo', generation_id=112, member_id=u'kafka-python-1.3.5-1220fe0a-2275-40c9-bd0a-68ea3837824d', group_assignment=[(member_id=u'kafka-python-1.3.5-1220fe0a-2275-40c9-bd0a-68ea3837824d', member_metadata='\x00\x00\x00\x00\x00\x01\x00 function_topic\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00')])
2018-03-12 03:19:36,061 - kafka.conn - DEBUG - <BrokerConnection node_id=1001 host=kafka-0.broker.kubeless.svc.cluster.local/172.17.0.5 port=9092> Response 6: SyncGroupResponse_v0(error_code=0, member_assignment='\x00\x00\x00\x00\x00\x01\x00 function_topic\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00')
2018-03-12 03:19:36,061 - kafka.coordinator - INFO - Successfully joined group parsefoo with generation 112
2018-03-12 03:19:36,062 - kafka.consumer.subscription_state - INFO - Updated partition assignment: [TopicPartition(topic=u’function_topic’, partition=0)]
2018-03-12 03:19:36,062 - kafka.coordinator.consumer - INFO - Setting newly assigned partitions set([TopicPartition(topic=u’function_topic’, partition=0)]) for group parsefoo
2018-03-12 03:19:36,063 - kafka.coordinator.consumer - DEBUG - Group parsefoo fetching committed offsets for partitions: set([TopicPartition(topic=u’function_topic’, partition=0)])
2018-03-12 03:19:36,063 - kafka.conn - DEBUG - <BrokerConnection node_id=1001 host=kafka-0.broker.kubeless.svc.cluster.local/172.17.0.5 port=9092> Request 7: OffsetFetchRequest_v1(consumer_group='parsefoo', topics=[(topic=u’function_topic’, partitions=[0])])
2018-03-12 03:19:36,063 - kafka.coordinator - DEBUG - Heartbeat task unneeded now, retrying in 2.99824309349
2018-03-12 03:19:36,065 - kafka.conn - DEBUG - <BrokerConnection node_id=1001 host=kafka-0.broker.kubeless.svc.cluster.local/172.17.0.5 port=9092> Response 7: OffsetFetchResponse_v1(topics=[(topic=u’function_topic’, partitions=[(partition=0, offset=79, metadata=u'', error_code=0)])])
2018-03-12 03:19:36,065 - kafka.consumer.fetcher - DEBUG - Resetting offset for partition TopicPartition(topic=u’function_topic’, partition=0) to the committed offset 79
2018-03-12 03:19:36,066 - kafka.consumer.fetcher - DEBUG - Adding fetch request for partition TopicPartition(topic=u’function_topic’, partition=0) at offset 79
2018-03-12 03:19:36,066 - kafka.consumer.fetcher - DEBUG - Sending FetchRequest to node 1001
2018-03-12 03:19:36,066 - kafka.conn - DEBUG - <BrokerConnection node_id=1001 host=kafka-0.broker.kubeless.svc.cluster.local/172.17.0.5 port=9092> Request 8: FetchRequest_v3(replica_id=-1, max_wait_time=500, min_bytes=1, max_bytes=52428800, topics=[(topic=u’function_topic’, partitions=[(partition=0, offset=79, max_bytes=1048576)])])
2018-03-12 03:19:36,067 - kafka.conn - DEBUG - <BrokerConnection node_id=1001 host=kafka-0.broker.kubeless.svc.cluster.local/172.17.0.5 port=9092> Response 8: FetchResponse_v3(throttle_time_ms=0, topics=[(topics=u’function_topic’, partitions=[(partition=0, error_code=0, highwater_offset=81, message_set=['(offset=79, message=22)', '(offset=80, message=26)'])])])
2018-03-12 03:19:36,068 - kafka.consumer.fetcher - DEBUG - Adding fetched record for partition TopicPartition(topic=u’function_topic’, partition=0) with offset 79 to buffered record list
2018-03-12 03:19:36,068 - kafka.metrics.metrics - DEBUG - Added sensor with name topic.function_topic.bytes-fetched
2018-03-12 03:19:36,068 - kafka.metrics.metrics - DEBUG - Added sensor with name topic.function_topic.records-fetched
2018-03-12 03:19:37,922 - kafka.producer.kafka - DEBUG - Sending (key=None value={'foo': 'bar'}) to TopicPartition(topic='next_function_topic', partition=0)
2018-03-12 03:19:37,922 - kafka.producer.record_accumulator - DEBUG - Allocating a new 16384 byte message buffer for TopicPartition(topic='next_function_topic', partition=0)
2018-03-12 03:19:37,923 - kafka.producer.kafka - DEBUG - Waking up the sender since TopicPartition(topic='next_function_topic', partition=0) is either full or getting a new batch
```

**Comment by jeffwidman** [comment]
Can you try this again with the new `1.4.6` release?

**Comment by Gonzalo933** [comment]
> Can you try this again with the new `1.4.6` release?

Still happening in 1.4.6

**Comment by Gareer** [comment]
I meet the same problem in 1.4.6

**Comment by radoslawkrolikowski** [comment]
Not sure if it is related to your issue, but I encountered the same problem while passing `producer` object to another function/method that utilizes multiprocessing (`billiard`), also when I tried to pass `producer` to `scrapy` pipeline. It turned out that the solution to this is to simply instantiate kafka `producer` inside those functions/methods rather than passing it from outside, because `producer` cannot be shared across different processes.

**Comment by dpkp** [comment]
I believe this is fixed in 1.4.7

**Comment by teplinsky-maxim** [comment]
@radoslawkrolikowski, yep, you are exactly right! It is still not fixed in 2022, and, I guess, won't ever be fixed. `kafka-python==2.0.2`. Creating local instances for each Process helps

**Comment by datadogeog** [comment]
> @radoslawkrolikowski, yep, you are exactly right! It is still not fixed in 2022, and, I guess, won't ever be fixed. `kafka-python==2.0.2`. Creating local instances for each Process helps

Still an issue 4 months later, and we're still at version 2.0.2.

**Comment by msidana** [comment]
waiting for the fix.
