### ISSUE TITLE
Python3.7 ValueError: attempt to connect already-connected SSLSocket!

### ISSUE THREAD

**Issue by dwintergruen** [dpkp/kafka-python#1549]
Try to establish a producer with:

(python3.7 Mac OS high Sierra)

producer = KafkaProducer(bootstrap_servers='SERVER:9093', ssl_password="XXXXX",
                              ssl_cafile="/etc/kafka_clients/ca-cert", security_protocol="SSL",
                              ssl_certfile="/etc/kafka_clients/cert-signed",
                              ssl_keyfile="/etc/kafka_clients/private-key")

always get:

 File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/kafka/producer/kafka.py", line 362, in __init__
    **self.config)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/kafka/client_async.py", line 214, in __init__
    self._bootstrap(collect_hosts(self.config['bootstrap_servers']))
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/kafka/client_async.py", line 245, in _bootstrap
    if not bootstrap.connect_blocking():
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/kafka/conn.py", line 301, in connect_blocking
    self.connect()
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/kafka/conn.py", line 354, in connect
    ret = self._sock.connect_ex(self._sock_addr)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 1146, in connect_ex
    return self._real_connect(addr, True)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 1118, in _real_connect
    raise ValueError("attempt to connect already-connected SSLSocket!")
ValueError: attempt to connect already-connected SSLSocket!

**Comment by freeyoung** [comment]
I'm getting exactly the same exception. Python 3.6 & 3.5 work prefectly.

**Comment by bunnyc1986** [comment]
I am getting the same error. Python 3.7 as well.

**Comment by apoclyps** [comment]
I've encountered the same problem described above whilst upgrading to `python:3.7-alpine`. I've created a test case which should allow easy reproduction of the [issue](https://gist.github.com/apoclyps/e3909ba54aa93bba293d4983a74e1cf8).

I've attempted to experiment with different `kafka-python` versions but found the issue described above limited to 1.4.3. `1.4.2` produces a different issue, outlined separately in [issue](https://gist.github.com/apoclyps/e3909ba54aa93bba293d4983a74e1cf8)

**Comment by matthieugouel** [comment]
Hello, 

As @bunnyc1986 pointed out, it has to do with a modification of the SSL module of CPython. I tried to remove the `self._sslobj is not None` of the line 1108 and it worked perfectly, but I guess the underlaying issue comes from `kafka-python` which may try to do a connection with the same socket multiple times. 

It's a little annoying because it prevents us to upgrade python to 3.7 just for that tiny issue ...

**Comment by richtera** [comment]
Any news on this?

**Comment by jeffwidman** [comment]
A PR would be welcome from someone who can test on permutations of SSL enabled / disabled for python 2.7, 3.6, and 3.7.

**Comment by dpkp** [comment]
We are waiting for a kind soul like yourself to develop a fix, test it with
different python/ssl configurations, and submit a PR.

**Comment by T-baby** [comment]
Come and see it every day. When can python-kafka fix this problem?

**Comment by dpkp** [comment]
kafka-python fix is one PR away! Will happily accept your improvements!

**Comment by seanthegeek** [comment]
@dpkp Here's that PR :)

**Comment by silentben** [comment]
@dpkp Looks like both @seanthegeek and I have submitted pull requests to fix this. Anything you're looking for before merging one or the other?

**Comment by jeffwidman** [comment]
Fixed by https://github.com/dpkp/kafka-python/pull/1669

**Comment by slyons** [comment]
This is still an issue in the current release. Any chances of a newer release?
